version = 3.8.1
runner.dialect = scala3

fileOverride {
  ".sc" {
    runner.dialect = scala213
  }
}

preset = IntelliJ
maxColumn = 100
align.preset = most

indent.main = 4
indent.callSite = 4
indent.defnSite = 4
indent.matchSite = 0

rewrite.scala3.convertToNewSyntax = true
rewrite.scala3.removeOptionalBraces = yes
rewrite.scala3.insertEndMarkerMinLines = 30
rewrite.scala3.removeEndMarkerMaxLines = 29
