version = 3.8.1
runner.dialect = scala3

fileOverride {
  ".mill" {
    runner.dialect = scala213
  }
}

preset = IntelliJ
maxColumn = 120
align.preset = most

indent {
    main = 2
    callSite = 2
    defnSite = 2
    matchSite = 2
}

rewrite.scala3 {
    convertToNewSyntax = true
    removeOptionalBraces {
        enabled = true
        oldSyntaxToo = true
    }
    insertEndMarkerMinLines = 30
    removeEndMarkerMaxLines = 29
}
