version = 3.8.2
runner.dialect = scala3

fileOverride {
  ".sc" {
    runner.dialect = scala213
  }
}

preset = IntelliJ
maxColumn = 100
align.preset = most

indent {
    main = 4
    callSite = 4
    defnSite = 4
    matchSite = 0
}

rewrite.scala3 {
    convertToNewSyntax = true
    removeOptionalBraces {
        enabled = true
        oldSyntaxToo = true
    }
    insertEndMarkerMinLines = 30
    removeEndMarkerMaxLines = 29
}
