services:
    database:
        image: postgres:latest
        environment:
            - POSTGRES_USER=ictdb
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=ictdb
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        restart: unless-stopped

volumes:
    postgres_data:
