services:
    database:
        image: postgres:latest
        environment:
            - POSTGRES_USER=ictdb
            - POSTGRES_PASSWORD=ictdb
            - POSTGRES_DB=ictdb
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
        driver: local
